### ISSUE TITLE
Project no longer works

### ISSUE THREAD

**Issue by JordanGarciaDev** [Ethic41/FingerPrint#21]
Docker version is outdated, the project is no longer running.

Any new updates in 2024?

**Comment by ivinson** [comment]
I am currently using Docker without any issues in my application.

**Comment by aymmuazu** [comment]
> I am currently using Docker without any issues in my application.

Please can you help me with the steps you follow to ensure the docker is installed etc. Because i'm having error such as:

[Sun Dec  8 12:35:07 2024] 127.0.0.1:34014 [500]: POST /src/core/enroll.php - Uncaught WpOrg\Requests\Exception: cURL error 28: Operation timed out after 10004 milliseconds with 0 bytes received in /home/hacker/Code/php/studentprojects/biometricattendance/FingerPrint/src/core/helpers/Requests/src/Transport/Curl.php:493
Stack trace:
#0 /home/hacker/Code/php/studentprojects/biometricattendance/FingerPrint/src/core/helpers/Requests/src/Transport/Curl.php(219): WpOrg\Requests\Transport\Curl->process_response()
#1 /home/hacker/Code/php/studentprojects/biometricattendance/FingerPrint/src/core/helpers/Requests/src/Requests.php(470): WpOrg\Requests\Transport\Curl->request()
#2 /home/hacker/Code/php/studentprojects/biometricattendance/FingerPrint/src/core/helpers/Requests/src/Requests.php(342): WpOrg\Requests\Requests::request()
#3 /home/hacker/Code/php/studentprojects/biometricattendance/FingerPrint/src/core/helpers/helpers.php(109): WpOrg\Requests\Requests::post()
#4 /home/hacker/Code/php/studentprojects/biometricattendance/FingerPrint/src/core/helpers/helpers.php(29): make_request()
#5 /home/hacker/Code/php/studentprojects/biometricattendance/FingerPrint/src/core/enroll.php(35): enroll_fingerprint()
#6 {main}
  thrown in /home/hacker/Code/php/studentprojects/biometricattendance/FingerPrint/src/core/helpers/Requests/src/Transport/Curl.php on line 493
[Sun Dec  8 12:35:07 2024] 127.0.0.1:34014 Closing
[Sun Dec  8 12:35:07 2024] 127.0.0.1:34016 Accepted
[Sun Dec  8 12:35:07 2024] 127.0.0.1:34016 [404]: POST /coreComponents/enroll.php - No such file or directory
[Sun Dec  8 12:35:07 2024] 127.0.0.1:34016 Closing
